// คำศัพท์ ม.5 เทอม 1 — ใช้ร่วมกันระหว่างหน้า player กับ server action
// deckId ต้องตรงกับ fixed UUID ใน migration 0007

export type FlashcardCard = { id: string; word: string; meaning: string };

export type FlashcardUnit = {
  deckId: string;
  name: string;
  cards: FlashcardCard[];
};

export const M5_TERM1_UNITS: FlashcardUnit[] = [
  {
    deckId: "a1000000-0000-4000-8000-000000000001",
    name: "Unit 1.1 Right Brain, Left Brain",
    cards: [
      { id: "u1r1-1", word: "to have something in common", meaning: "มีบางอย่างเหมือนกัน" },
      { id: "u1r1-2", word: "population", meaning: "ประชากร" },
      { id: "u1r1-3", word: "a message", meaning: "ข้อความ" },
      { id: "u1r1-4", word: "punctual", meaning: "ตรงเวลา" },
      { id: "u1r1-5", word: "logic", meaning: "ตรรกะ" },
      { id: "u1r1-6", word: "in order", meaning: "ถูกกาลเทศะ" },
      { id: "u1r1-7", word: "to recognize", meaning: "ระลึกถึง" },
      { id: "u1r1-8", word: "exceptions", meaning: "ข้อยกเว้น" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000002",
    name: "Unit 1.2 Let's Face It",
    cards: [
      { id: "u1r2-1", word: "a jaw", meaning: "กราม" },
      { id: "u1r2-2", word: "cheekbones", meaning: "โหนกแก้ม" },
      { id: "u1r2-3", word: "confident", meaning: "มั่นใจ" },
      { id: "u1r2-4", word: "a will", meaning: "ความพยายาม / มุมานะ" },
      { id: "u1r2-5", word: "creative", meaning: "สร้างสรรค์" },
      { id: "u1r2-6", word: "reliable", meaning: "พึ่งพาได้" },
      { id: "u1r2-7", word: "generous", meaning: "ใจกว้าง / ใจดี" },
      { id: "u1r2-8", word: "fragile", meaning: "บอบบาง / แตกง่าย" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000003",
    name: "Unit 2.1 Eat Potatoes!",
    cards: [
      { id: "u2r1-1", word: "to imagine", meaning: "จินตนาการ" },
      { id: "u2r1-2", word: "instead", meaning: "แทนที่จะ" },
      { id: "u2r1-3", word: "a poison", meaning: "ยาพิษ" },
      { id: "u2r1-4", word: "advantages", meaning: "ประโยชน์" },
      { id: "u2r1-5", word: "a disease", meaning: "โรค" },
      { id: "u2r1-6", word: "dishes", meaning: "เมนู" },
      { id: "u2r1-7", word: "baked", meaning: "อบ" },
      { id: "u2r1-8", word: "to invent", meaning: "ประดิษฐ์" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000004",
    name: "Unit 2.2 Tasty Dishes",
    cards: [
      { id: "u2r2-1", word: "a delicacy", meaning: "อาหารอันโอชะ" },
      { id: "u2r2-2", word: "an appetizer", meaning: "อาหารเรียกน้ำย่อย" },
      { id: "u2r2-3", word: "alive", meaning: "ยังมีชีวิต" },
      { id: "u2r2-4", word: "desserts", meaning: "ของหวาน" },
      { id: "u2r2-5", word: "pork", meaning: "หมู" },
      { id: "u2r2-6", word: "grilled", meaning: "ย่าง" },
      { id: "u2r2-7", word: "a paste", meaning: "เนื้อบด / ซอส" },
      { id: "u2r2-8", word: "native", meaning: "ท้องถิ่น" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000005",
    name: "Unit 3.1 Tihar — Festival of Lights",
    cards: [
      { id: "u3r1-1", word: "to worship", meaning: "สักการะ / แสดงบูชา" },
      { id: "u3r1-2", word: "stray", meaning: "ไม่มีบ้าน / จรจัด" },
      { id: "u3r1-3", word: "holy", meaning: "ศักดิ์สิทธิ์" },
      { id: "u3r1-4", word: "to please", meaning: "ทำให้พอใจ" },
      { id: "u3r1-5", word: "mud", meaning: "โคลน" },
      { id: "u3r1-6", word: "a trail", meaning: "ทางเดิน" },
      { id: "u3r1-7", word: "an icon", meaning: "สัญลักษณ์บูชา" },
      { id: "u3r1-8", word: "prosperity", meaning: "ความมั่งคั่ง" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000006",
    name: "Unit 3.2 Fifteenth Birthday",
    cards: [
      { id: "u3r2-1", word: "godparents", meaning: "พ่อแม่อุปถัมภ์" },
      { id: "u3r2-2", word: "guests", meaning: "แขก" },
      { id: "u3r2-3", word: "to afford", meaning: "มีเงินพอจ่าย" },
      { id: "u3r2-4", word: "a bouquet", meaning: "ช่อดอกไม้" },
      { id: "u3r2-5", word: "blessings", meaning: "พร / การอวยพร" },
      { id: "u3r2-6", word: "proud of", meaning: "ภูมิใจใน" },
      { id: "u3r2-7", word: "grown-up", meaning: "ผู้ใหญ่" },
      { id: "u3r2-8", word: "to pose", meaning: "โพสท่า" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000007",
    name: "Unit 4.1 Dream to Fly",
    cards: [
      { id: "u4r1-1", word: "solo", meaning: "คนเดียว / โดดเดี่ยว" },
      { id: "u4r1-2", word: "determined", meaning: "มุ่งมั่น" },
      { id: "u4r1-3", word: "neighborhoods", meaning: "ละแวกบ้าน" },
      { id: "u4r1-4", word: "careers", meaning: "อาชีพ" },
      { id: "u4r1-5", word: "a license", meaning: "ใบอนุญาต" },
      { id: "u4r1-6", word: "a limit", meaning: "ขีดจำกัด" },
      { id: "u4r1-7", word: "equipment", meaning: "อุปกรณ์" },
      { id: "u4r1-8", word: "to solve problems", meaning: "แก้ปัญหา" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000008",
    name: "Unit 4.2 The Fearless Fiennes",
    cards: [
      { id: "u4r2-1", word: "records", meaning: "สถิติ" },
      { id: "u4r2-2", word: "to raise money", meaning: "ระดมทุน" },
      { id: "u4r2-3", word: "charities", meaning: "กุศล / องค์กรการกุศล" },
      { id: "u4r2-4", word: "to reach", meaning: "ถึง" },
      { id: "u4r2-5", word: "extreme", meaning: "สุดขีด" },
      { id: "u4r2-6", word: "surgery", meaning: "การผ่าตัด" },
      { id: "u4r2-7", word: "to get rid of", meaning: "กำจัด / เอาออก" },
      { id: "u4r2-8", word: "to give up", meaning: "ยอมแพ้" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000009",
    name: "Unit 5.1 Lightning",
    cards: [
      { id: "u5r1-1", word: "lightning bolts", meaning: "สายฟ้าฟาด" },
      { id: "u5r1-2", word: "to amaze", meaning: "ทำให้ประหลาดใจ" },
      { id: "u5r1-3", word: "to frighten", meaning: "ทำให้กลัว" },
      { id: "u5r1-4", word: "injured", meaning: "ได้รับบาดเจ็บ" },
      { id: "u5r1-5", word: "to explode", meaning: "ระเบิด" },
      { id: "u5r1-6", word: "to protect", meaning: "ปกป้อง" },
      { id: "u5r1-7", word: "a shelter", meaning: "ที่หลบภัย" },
      { id: "u5r1-8", word: "to attract", meaning: "ดึงดูด" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000010",
    name: "Unit 5.2 Chasing Storms",
    cards: [
      { id: "u5r2-1", word: "a focus", meaning: "จุดสนใจ / มุ่งความสนใจ" },
      { id: "u5r2-2", word: "brilliant", meaning: "ฉลาดหลักแหลม / ปราดเปรียว" },
      { id: "u5r2-3", word: "flat", meaning: "แบน" },
      { id: "u5r2-4", word: "to develop", meaning: "ก่อตัว" },
      { id: "u5r2-5", word: "to twist", meaning: "หมุน" },
      { id: "u5r2-6", word: "to destroy", meaning: "ทำลาย" },
      { id: "u5r2-7", word: "a path", meaning: "เส้นทาง" },
      { id: "u5r2-8", word: "forecasts", meaning: "พยากรณ์" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000011",
    name: "Unit 6.1 The GoPro Camera",
    cards: [
      { id: "u6r1-1", word: "to attach", meaning: "ติด / แนบ" },
      { id: "u6r1-2", word: "a vehicle", meaning: "ยานพาหนะ" },
      { id: "u6r1-3", word: "memorable", meaning: "น่าจดจำ" },
      { id: "u6r1-4", word: "to share", meaning: "แบ่งปัน" },
      { id: "u6r1-5", word: "disappointed", meaning: "ผิดหวัง" },
      { id: "u6r1-6", word: "at least", meaning: "อย่างน้อย" },
      { id: "u6r1-7", word: "training", meaning: "การฝึกฝน" },
      { id: "u6r1-8", word: "evidence", meaning: "หลักฐาน" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000012",
    name: "Unit 6.2 Changing Living Things?",
    cards: [
      { id: "u6r2-1", word: "a cell", meaning: "เซลล์" },
      { id: "u6r2-2", word: "genes", meaning: "ยีน" },
      { id: "u6r2-3", word: "crops", meaning: "พืชผล" },
      { id: "u6r2-4", word: "resistant", meaning: "ต้านทาน" },
      { id: "u6r2-5", word: "insecticides", meaning: "ยาฆ่าแมลง" },
      { id: "u6r2-6", word: "to wrap", meaning: "ห่อ" },
      { id: "u6r2-7", word: "to peel", meaning: "ปอกเปลือก" },
      { id: "u6r2-8", word: "to spill", meaning: "หกหรือทำล้น" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000013",
    name: "Unit 7.1 Flowers, Dishes, and Dress",
    cards: [
      { id: "u7r1-1", word: "charms", meaning: "เครื่องราง" },
      { id: "u7r1-2", word: "symbols", meaning: "สัญลักษณ์" },
      { id: "u7r1-3", word: "a bride", meaning: "เจ้าสาว" },
      { id: "u7r1-4", word: "a groom", meaning: "เจ้าบ่าว" },
      { id: "u7r1-5", word: "informal", meaning: "ไม่เป็นทางการ" },
      { id: "u7r1-6", word: "an aisle", meaning: "ทางเดินกลางโบสถ์" },
      { id: "u7r1-7", word: "faithfulness", meaning: "ความซื่อสัตย์" },
      { id: "u7r1-8", word: "a crown", meaning: "มงกุฎ" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000014",
    name: "Unit 7.2 What's in a Name?",
    cards: [
      { id: "u7r2-1", word: "occupations", meaning: "อาชีพ" },
      { id: "u7r2-2", word: "characteristics", meaning: "ลักษณะเฉพาะ" },
      { id: "u7r2-3", word: "a landmark", meaning: "สถานที่สำคัญ" },
      { id: "u7r2-4", word: "an abbreviation", meaning: "คำย่อ" },
      { id: "u7r2-5", word: "to honor", meaning: "ให้เกียรติ" },
      { id: "u7r2-6", word: "an initial", meaning: "อักษรย่อ" },
      { id: "u7r2-7", word: "paperwork", meaning: "งานเอกสาร" },
      { id: "u7r2-8", word: "a trademark", meaning: "เครื่องหมายการค้า" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000015",
    name: "Unit 8.1 Months",
    cards: [
      { id: "u8r1-1", word: "dripping wet", meaning: "เปียกโชก" },
      { id: "u8r1-2", word: "to rage", meaning: "คึกคะนอง / รุนแรง" },
      { id: "u8r1-3", word: "in tune", meaning: "ร้องเพลงถูกเสียง" },
      { id: "u8r1-4", word: "torn", meaning: "ถูกฉีกขาด" },
      { id: "u8r1-5", word: "to bear", meaning: "ผลิตผล" },
      { id: "u8r1-6", word: "rough", meaning: "ขรุขระ / รุนแรง" },
      { id: "u8r1-7", word: "to shoot", meaning: "งอกออกมา / ยิง" },
      { id: "u8r1-8", word: "bleak", meaning: "หม่นหมอง / ไร้ความหวัง" },
    ],
  },
  {
    deckId: "a1000000-0000-4000-8000-000000000016",
    name: "Unit 8.2 Fate",
    cards: [
      { id: "u8r2-1", word: "to refuse", meaning: "ปฏิเสธ" },
      { id: "u8r2-2", word: "fate", meaning: "โชคชะตา" },
      { id: "u8r2-3", word: "a journey", meaning: "การเดินทาง" },
      { id: "u8r2-4", word: "a stranger", meaning: "คนแปลกหน้า" },
      { id: "u8r2-5", word: "ill", meaning: "ป่วย" },
      { id: "u8r2-6", word: "horrified", meaning: "ตกใจกลัว / ขยะแขยง" },
      { id: "u8r2-7", word: "to prepare", meaning: "เตรียมพร้อม" },
      { id: "u8r2-8", word: "to cure", meaning: "รักษาโรค" },
    ],
  },
];
