// คำศัพท์ ม.6 พื้นฐาน — ใช้ร่วมกันระหว่างหน้า player กับ server action
// deckId ต้องตรงกับ fixed UUID ใน migration 0008

import type { FlashcardUnit } from "./m5-term-1-data";

export const M6_TERM2_UNITS: FlashcardUnit[] = [
  {
    deckId: "a2000000-0000-4000-8000-000000000001",
    name: "01 Getting Ready for College",
    cards: [
      { id: "b01-1", word: "association", meaning: "สมาคม, ความสัมพันธ์" },
      { id: "b01-2", word: "award", meaning: "รางวัล" },
      { id: "b01-3", word: "behalf", meaning: "ในนามของ" },
      { id: "b01-4", word: "capable", meaning: "มีความสามารถ" },
      { id: "b01-5", word: "competitive", meaning: "มีการแข่งขันสูง" },
      { id: "b01-6", word: "institution", meaning: "สถาบัน" },
      { id: "b01-7", word: "strength", meaning: "จุดแข็ง" },
      { id: "b01-8", word: "weakness", meaning: "จุดอ่อน" },
      { id: "b01-9", word: "assume", meaning: "สมมติ, คิดว่า" },
      { id: "b01-10", word: "circumstance", meaning: "สถานการณ์" },
      { id: "b01-11", word: "commit", meaning: "อุทิศตน, กระทำ" },
      { id: "b01-12", word: "cope", meaning: "รับมือ" },
      { id: "b01-13", word: "intention", meaning: "ความตั้งใจ" },
      { id: "b01-14", word: "respond", meaning: "ตอบสนอง" },
      { id: "b01-15", word: "sufficient", meaning: "เพียงพอ" },
      { id: "b01-16", word: "tough", meaning: "ยาก, แข็งแกร่ง" },
      { id: "b01-17", word: "abandon", meaning: "ละทิ้ง" },
      { id: "b01-18", word: "betray", meaning: "ทรยศ" },
      { id: "b01-19", word: "collapse", meaning: "พังทลาย, ล้มเหลว" },
      { id: "b01-20", word: "combination", meaning: "การรวมกัน" },
      { id: "b01-21", word: "encounter", meaning: "พบเจอ" },
      { id: "b01-22", word: "occur", meaning: "เกิดขึ้น" },
      { id: "b01-23", word: "reputation", meaning: "ชื่อเสียง" },
      { id: "b01-24", word: "suspicious", meaning: "น่าสงสัย" },
      { id: "b01-25", word: "deliberate", meaning: "จงใจ, ไตร่ตรอง" },
      { id: "b01-26", word: "ideal", meaning: "อุดมคติ, เหมาะสมที่สุด" },
      { id: "b01-27", word: "initially", meaning: "ในตอนแรก" },
      { id: "b01-28", word: "outstanding", meaning: "โดดเด่น" },
      { id: "b01-29", word: "overall", meaning: "โดยรวม" },
      { id: "b01-30", word: "relief", meaning: "ความโล่งใจ" },
      { id: "b01-31", word: "selection", meaning: "การคัดเลือก" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000002",
    name: "02 Time to Set Sail",
    cards: [
      { id: "b02-1", word: "aside from", meaning: "นอกจาก" },
      { id: "b02-2", word: "attractive", meaning: "น่าดึงดูด" },
      { id: "b02-3", word: "extensive", meaning: "กว้างขวาง" },
      { id: "b02-4", word: "instant", meaning: "ทันที" },
      { id: "b02-5", word: "perspective", meaning: "มุมมอง" },
      { id: "b02-6", word: "proud", meaning: "ภาคภูมิใจ" },
      { id: "b02-7", word: "quite", meaning: "ค่อนข้าง" },
      { id: "b02-8", word: "stunning", meaning: "งดงามมาก, น่าทึ่ง" },
      { id: "b02-9", word: "destination", meaning: "จุดหมายปลายทาง" },
      { id: "b02-10", word: "dreadful", meaning: "เลวร้าย" },
      { id: "b02-11", word: "exotic", meaning: "แปลกใหม่, ต่างถิ่น" },
      { id: "b02-12", word: "feature", meaning: "ลักษณะเด่น" },
      { id: "b02-13", word: "nonetheless", meaning: "อย่างไรก็ตาม" },
      { id: "b02-14", word: "pirate", meaning: "โจรสลัด" },
      { id: "b02-15", word: "remarkable", meaning: "น่าทึ่ง" },
      { id: "b02-16", word: "shipwreck", meaning: "เรืออับปาง" },
      { id: "b02-17", word: "capture", meaning: "จับกุม, จับภาพ" },
      { id: "b02-18", word: "confirm", meaning: "ยืนยัน" },
      { id: "b02-19", word: "determine", meaning: "กำหนด, ตัดสินใจ" },
      { id: "b02-20", word: "drown", meaning: "จมน้ำ" },
      { id: "b02-21", word: "insignificant", meaning: "ไม่สำคัญ" },
      { id: "b02-22", word: "seek", meaning: "แสวงหา" },
      { id: "b02-23", word: "tremendous", meaning: "มหาศาล" },
      { id: "b02-24", word: "unsophisticated", meaning: "ไม่ซับซ้อน" },
      { id: "b02-25", word: "astonishing", meaning: "น่าประหลาดใจ" },
      { id: "b02-26", word: "classify", meaning: "จัดประเภท" },
      { id: "b02-27", word: "furthermore", meaning: "นอกจากนี้" },
      { id: "b02-28", word: "port", meaning: "ท่าเรือ" },
      { id: "b02-29", word: "priceless", meaning: "ล้ำค่า" },
      { id: "b02-30", word: "sail", meaning: "แล่นเรือ" },
      { id: "b02-31", word: "therefore", meaning: "ดังนั้น" },
      { id: "b02-32", word: "voyage", meaning: "การเดินทางทางทะเล" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000003",
    name: "03 Healthy Thinking",
    cards: [
      { id: "b03-1", word: "adjust", meaning: "ปรับตัว" },
      { id: "b03-2", word: "balance", meaning: "สมดุล" },
      { id: "b03-3", word: "crucial", meaning: "สำคัญมาก" },
      { id: "b03-4", word: "current", meaning: "ปัจจุบัน" },
      { id: "b03-5", word: "enable", meaning: "ทำให้สามารถ" },
      { id: "b03-6", word: "eventually", meaning: "ในที่สุด" },
      { id: "b03-7", word: "maintain", meaning: "รักษาไว้" },
      { id: "b03-8", word: "monitor", meaning: "ติดตาม, เฝ้าดู" },
      { id: "b03-9", word: "affect", meaning: "ส่งผลกระทบ" },
      { id: "b03-10", word: "anxiety", meaning: "ความวิตกกังวล" },
      { id: "b03-11", word: "conventional", meaning: "แบบดั้งเดิม" },
      { id: "b03-12", word: "faith", meaning: "ความศรัทธา" },
      { id: "b03-13", word: "gradual", meaning: "ค่อยเป็นค่อยไป" },
      { id: "b03-14", word: "practical", meaning: "ใช้งานได้จริง" },
      { id: "b03-15", word: "restore", meaning: "ฟื้นฟู" },
      { id: "b03-16", word: "suffer", meaning: "ทนทุกข์" },
      { id: "b03-17", word: "ensure", meaning: "ทำให้มั่นใจ" },
      { id: "b03-18", word: "factor", meaning: "ปัจจัย" },
      { id: "b03-19", word: "infection", meaning: "การติดเชื้อ" },
      { id: "b03-20", word: "massive", meaning: "มหาศาล" },
      { id: "b03-21", word: "medical", meaning: "ทางการแพทย์" },
      { id: "b03-22", word: "needle", meaning: "เข็ม" },
      { id: "b03-23", word: "potential", meaning: "ศักยภาพ, ที่เป็นไปได้" },
      { id: "b03-24", word: "treatment", meaning: "การรักษา" },
      { id: "b03-25", word: "alter", meaning: "เปลี่ยนแปลง" },
      { id: "b03-26", word: "appeal", meaning: "ดึงดูดใจ" },
      { id: "b03-27", word: "artificial", meaning: "เทียม, สังเคราะห์" },
      { id: "b03-28", word: "aware", meaning: "ตระหนักรู้" },
      { id: "b03-29", word: "expectation", meaning: "ความคาดหวัง" },
      { id: "b03-30", word: "poisonous", meaning: "มีพิษ" },
      { id: "b03-31", word: "state", meaning: "สภาพ, สถานะ" },
      { id: "b03-32", word: "valid", meaning: "ถูกต้อง, ใช้ได้" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000004",
    name: "04 Money Talks",
    cards: [
      { id: "b04-1", word: "charge", meaning: "คิดค่าบริการ" },
      { id: "b04-2", word: "foolish", meaning: "โง่เขลา" },
      { id: "b04-3", word: "keep track", meaning: "ติดตาม, จดบันทึก" },
      { id: "b04-4", word: "mature", meaning: "เป็นผู้ใหญ่" },
      { id: "b04-5", word: "percentage", meaning: "ร้อยละ" },
      { id: "b04-6", word: "substantial", meaning: "จำนวนมาก" },
      { id: "b04-7", word: "typical", meaning: "โดยทั่วไป" },
      { id: "b04-8", word: "wise", meaning: "ฉลาด" },
      { id: "b04-9", word: "assess", meaning: "ประเมิน" },
      { id: "b04-10", word: "dedicated", meaning: "ทุ่มเท" },
      { id: "b04-11", word: "interest", meaning: "ดอกเบี้ย, ความสนใจ" },
      { id: "b04-12", word: "management", meaning: "การจัดการ" },
      { id: "b04-13", word: "panic", meaning: "ตื่นตระหนก" },
      { id: "b04-14", word: "point", meaning: "ประเด็น" },
      { id: "b04-15", word: "rate", meaning: "อัตรา" },
      { id: "b04-16", word: "upset", meaning: "ไม่สบายใจ" },
      { id: "b04-17", word: "consumer", meaning: "ผู้บริโภค" },
      { id: "b04-18", word: "deal", meaning: "ข้อตกลง" },
      { id: "b04-19", word: "evaluate", meaning: "ประเมินค่า" },
      { id: "b04-20", word: "exclusive", meaning: "พิเศษเฉพาะ" },
      { id: "b04-21", word: "impact", meaning: "ผลกระทบ" },
      { id: "b04-22", word: "moderate", meaning: "ปานกลาง" },
      { id: "b04-23", word: "recession", meaning: "ภาวะเศรษฐกิจถดถอย" },
      { id: "b04-24", word: "standard", meaning: "มาตรฐาน" },
      { id: "b04-25", word: "addiction", meaning: "การเสพติด" },
      { id: "b04-26", word: "allowance", meaning: "เงินค่าขนม" },
      { id: "b04-27", word: "debit card", meaning: "บัตรเดบิต" },
      { id: "b04-28", word: "guidance", meaning: "คำแนะนำ" },
      { id: "b04-29", word: "level", meaning: "ระดับ" },
      { id: "b04-30", word: "obsession", meaning: "ความหมกมุ่น" },
      { id: "b04-31", word: "transfer", meaning: "โอน" },
      { id: "b04-32", word: "withdraw", meaning: "ถอน" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000005",
    name: "05 Cultures Around the World",
    cards: [
      { id: "b05-1", word: "concept", meaning: "แนวคิด" },
      { id: "b05-2", word: "exceptional", meaning: "ยอดเยี่ยมเป็นพิเศษ" },
      { id: "b05-3", word: "familiar", meaning: "คุ้นเคย" },
      { id: "b05-4", word: "unfamiliar", meaning: "ไม่คุ้นเคย" },
      { id: "b05-5", word: "manners", meaning: "มารยาท" },
      { id: "b05-6", word: "obey", meaning: "เชื่อฟัง" },
      { id: "b05-7", word: "disobey", meaning: "ไม่เชื่อฟัง" },
      { id: "b05-8", word: "peculiar", meaning: "แปลกประหลาด" },
      { id: "b05-9", word: "strict", meaning: "เข้มงวด" },
      { id: "b05-10", word: "vary", meaning: "แตกต่างกัน" },
      { id: "b05-11", word: "accent", meaning: "สำเนียง" },
      { id: "b05-12", word: "criticize", meaning: "วิจารณ์" },
      { id: "b05-13", word: "frustrating", meaning: "น่าหงุดหงิด" },
      { id: "b05-14", word: "harsh", meaning: "รุนแรง" },
      { id: "b05-15", word: "insult", meaning: "ดูหมิ่น" },
      { id: "b05-16", word: "major", meaning: "หลัก, สำคัญ" },
      { id: "b05-17", word: "minor", meaning: "รอง, เล็กน้อย" },
      { id: "b05-18", word: "native", meaning: "เจ้าของภาษา" },
      { id: "b05-19", word: "straightforward", meaning: "ตรงไปตรงมา" },
      { id: "b05-20", word: "aspect", meaning: "แง่มุม" },
      { id: "b05-21", word: "campus", meaning: "วิทยาเขต" },
      { id: "b05-22", word: "diverse", meaning: "หลากหลาย" },
      { id: "b05-23", word: "identity", meaning: "อัตลักษณ์" },
      { id: "b05-24", word: "outgoing", meaning: "เข้าสังคมเก่ง" },
      { id: "b05-25", word: "overwhelm", meaning: "ทำให้รู้สึกท่วมท้น" },
      { id: "b05-26", word: "pause", meaning: "หยุดชั่วคราว" },
      { id: "b05-27", word: "reserved", meaning: "เก็บตัว" },
      { id: "b05-28", word: "approve", meaning: "เห็นด้วย" },
      { id: "b05-29", word: "disapprove", meaning: "ไม่เห็นด้วย" },
      { id: "b05-30", word: "gesture", meaning: "ท่าทาง" },
      { id: "b05-31", word: "honor", meaning: "ให้เกียรติ" },
      { id: "b05-32", word: "host", meaning: "เจ้าภาพ" },
      { id: "b05-33", word: "indicate", meaning: "บ่งชี้" },
      { id: "b05-34", word: "knock", meaning: "เคาะ" },
      { id: "b05-35", word: "lap", meaning: "ตัก" },
      { id: "b05-36", word: "specific", meaning: "เฉพาะเจาะจง" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000006",
    name: "06 It's a Masterpiece!",
    cards: [
      { id: "b06-1", word: "abstract", meaning: "นามธรรม" },
      { id: "b06-2", word: "commercial", meaning: "เชิงพาณิชย์" },
      { id: "b06-3", word: "dialogue", meaning: "บทสนทนา" },
      { id: "b06-4", word: "novelist", meaning: "นักประพันธ์นวนิยาย" },
      { id: "b06-5", word: "observation", meaning: "การสังเกต" },
      { id: "b06-6", word: "release", meaning: "เผยแพร่" },
      { id: "b06-7", word: "script", meaning: "บทภาพยนตร์" },
      { id: "b06-8", word: "violent", meaning: "รุนแรง" },
      { id: "b06-9", word: "bizarre", meaning: "ประหลาด" },
      { id: "b06-10", word: "contemporary", meaning: "ร่วมสมัย" },
      { id: "b06-11", word: "context", meaning: "บริบท" },
      { id: "b06-12", word: "feelings", meaning: "ความรู้สึก" },
      { id: "b06-13", word: "lyrics", meaning: "เนื้อเพลง" },
      { id: "b06-14", word: "rhythm", meaning: "จังหวะ" },
      { id: "b06-15", word: "tone", meaning: "น้ำเสียง" },
      { id: "b06-16", word: "unfashionable", meaning: "ไม่ทันสมัย" },
      { id: "b06-17", word: "classic", meaning: "คลาสสิก" },
      { id: "b06-18", word: "controversial", meaning: "เป็นที่ถกเถียง" },
      { id: "b06-19", word: "critic", meaning: "นักวิจารณ์" },
      { id: "b06-20", word: "mass media", meaning: "สื่อมวลชน" },
      { id: "b06-21", word: "portrait", meaning: "ภาพเหมือน" },
      { id: "b06-22", word: "scene", meaning: "ฉาก" },
      { id: "b06-23", word: "striking", meaning: "โดดเด่นสะดุดตา" },
      { id: "b06-24", word: "visual", meaning: "เกี่ยวกับการมองเห็น" },
      { id: "b06-25", word: "absorbed", meaning: "หมกมุ่น" },
      { id: "b06-26", word: "colorful", meaning: "มีสีสัน" },
      { id: "b06-27", word: "compromise", meaning: "ประนีประนอม" },
      { id: "b06-28", word: "glance", meaning: "ชำเลืองมอง" },
      { id: "b06-29", word: "solo", meaning: "เดี่ยว" },
      { id: "b06-30", word: "soul", meaning: "จิตวิญญาณ" },
      { id: "b06-31", word: "tale", meaning: "เรื่องเล่า" },
      { id: "b06-32", word: "terrifying", meaning: "น่ากลัว" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000007",
    name: "07 Deciding for Yourself",
    cards: [
      { id: "b07-1", word: "fluent", meaning: "คล่องแคล่ว" },
      { id: "b07-2", word: "get over", meaning: "ผ่านพ้น" },
      { id: "b07-3", word: "independence", meaning: "ความเป็นอิสระ" },
      { id: "b07-4", word: "keep (sb.) company", meaning: "อยู่เป็นเพื่อน" },
      { id: "b07-5", word: "socialize", meaning: "เข้าสังคม" },
      { id: "b07-6", word: "sympathy", meaning: "ความเห็นอกเห็นใจ" },
      { id: "b07-7", word: "tremble", meaning: "สั่น" },
      { id: "b07-8", word: "vivid", meaning: "ชัดเจน" },
      { id: "b07-9", word: "blame", meaning: "โทษ" },
      { id: "b07-10", word: "constantly", meaning: "อย่างต่อเนื่อง" },
      { id: "b07-11", word: "deal with", meaning: "จัดการกับ" },
      { id: "b07-12", word: "distract", meaning: "ทำให้เสียสมาธิ" },
      { id: "b07-13", word: "earnings", meaning: "รายได้" },
      { id: "b07-14", word: "mess up", meaning: "ทำพัง" },
      { id: "b07-15", word: "skilled", meaning: "มีทักษะ" },
      { id: "b07-16", word: "temptation", meaning: "สิ่งยั่วยวน" },
      { id: "b07-17", word: "adventurous", meaning: "ชอบผจญภัย" },
      { id: "b07-18", word: "ecological", meaning: "เกี่ยวกับสิ่งแวดล้อม" },
      { id: "b07-19", word: "lovely", meaning: "น่ารัก" },
      { id: "b07-20", word: "miss out", meaning: "พลาดโอกาส" },
      { id: "b07-21", word: "profession", meaning: "อาชีพ" },
      { id: "b07-22", word: "responsibility", meaning: "ความรับผิดชอบ" },
      { id: "b07-23", word: "thrilled", meaning: "ตื่นเต้นมาก" },
      { id: "b07-24", word: "tropical", meaning: "เขตร้อน" },
      { id: "b07-25", word: "coward", meaning: "คนขี้ขลาด" },
      { id: "b07-26", word: "embarrassment", meaning: "ความอับอาย" },
      { id: "b07-27", word: "friendliness", meaning: "ความเป็นมิตร" },
      { id: "b07-28", word: "furious", meaning: "โกรธมาก" },
      { id: "b07-29", word: "popularity", meaning: "ความนิยม" },
      { id: "b07-30", word: "rumor", meaning: "ข่าวลือ" },
      { id: "b07-31", word: "severe", meaning: "รุนแรง" },
      { id: "b07-32", word: "trivial", meaning: "เล็กน้อย" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000008",
    name: "08 Crime Wave",
    cards: [
      { id: "b08-1", word: "barrier", meaning: "อุปสรรค" },
      { id: "b08-2", word: "beyond", meaning: "เกินกว่า" },
      { id: "b08-3", word: "contrasting", meaning: "แตกต่างกัน" },
      { id: "b08-4", word: "explosion", meaning: "การระเบิด" },
      { id: "b08-5", word: "force", meaning: "กำลัง, บังคับ" },
      { id: "b08-6", word: "incident", meaning: "เหตุการณ์" },
      { id: "b08-7", word: "react", meaning: "ตอบสนอง" },
      { id: "b08-8", word: "witness", meaning: "พยาน" },
      { id: "b08-9", word: "accuse", meaning: "กล่าวหา" },
      { id: "b08-10", word: "assure", meaning: "รับรอง" },
      { id: "b08-11", word: "cheat", meaning: "โกง" },
      { id: "b08-12", word: "conflict", meaning: "ความขัดแย้ง" },
      { id: "b08-13", word: "hesitate", meaning: "ลังเล" },
      { id: "b08-14", word: "moral", meaning: "มีศีลธรรม" },
      { id: "b08-15", word: "immoral", meaning: "ไร้ศีลธรรม" },
      { id: "b08-16", word: "recall", meaning: "ระลึกได้" },
      { id: "b08-17", word: "threaten", meaning: "ข่มขู่" },
      { id: "b08-18", word: "adequate", meaning: "เพียงพอ" },
      { id: "b08-19", word: "authority", meaning: "อำนาจ" },
      { id: "b08-20", word: "devote", meaning: "อุทิศ" },
      { id: "b08-21", word: "justice", meaning: "ความยุติธรรม" },
      { id: "b08-22", word: "loyal", meaning: "ซื่อสัตย์" },
      { id: "b08-23", word: "nonsense", meaning: "ไร้สาระ" },
      { id: "b08-24", word: "resist", meaning: "ต่อต้าน" },
      { id: "b08-25", word: "scheme", meaning: "แผนการ" },
      { id: "b08-26", word: "bad-tempered", meaning: "อารมณ์เสียบ่อย" },
      { id: "b08-27", word: "investigate", meaning: "สืบสวน" },
      { id: "b08-28", word: "launch", meaning: "เริ่มต้น" },
      { id: "b08-29", word: "observe", meaning: "สังเกต" },
      { id: "b08-30", word: "relevant", meaning: "เกี่ยวข้อง" },
      { id: "b08-31", word: "suspect", meaning: "ผู้ต้องสงสัย, สงสัย" },
      { id: "b08-32", word: "swear", meaning: "สาบาน" },
      { id: "b08-33", word: "version", meaning: "เวอร์ชัน, รูปแบบ" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000009",
    name: "09 Eat Up!",
    cards: [
      { id: "b09-1", word: "dairy", meaning: "ผลิตภัณฑ์จากนม" },
      { id: "b09-2", word: "mint", meaning: "สะระแหน่" },
      { id: "b09-3", word: "pancake", meaning: "แพนเค้ก" },
      { id: "b09-4", word: "rich", meaning: "เข้มข้น" },
      { id: "b09-5", word: "spice", meaning: "เครื่องเทศ" },
      { id: "b09-6", word: "starving", meaning: "หิวมาก" },
      { id: "b09-7", word: "substitute", meaning: "สิ่งทดแทน" },
      { id: "b09-8", word: "texture", meaning: "เนื้อสัมผัส" },
      { id: "b09-9", word: "chaos", meaning: "ความวุ่นวาย" },
      { id: "b09-10", word: "combine", meaning: "รวมกัน" },
      { id: "b09-11", word: "evoke", meaning: "กระตุ้นให้เกิด" },
      { id: "b09-12", word: "feast", meaning: "งานเลี้ยง" },
      { id: "b09-13", word: "pan", meaning: "กระทะ" },
      { id: "b09-14", word: "pudding", meaning: "พุดดิ้ง" },
      { id: "b09-15", word: "roughly", meaning: "โดยประมาณ" },
      { id: "b09-16", word: "superb", meaning: "ยอดเยี่ยม" },
      { id: "b09-17", word: "affection", meaning: "ความรักใคร่" },
      { id: "b09-18", word: "destiny", meaning: "โชคชะตา" },
      { id: "b09-19", word: "enthusiasm", meaning: "ความกระตือรือร้น" },
      { id: "b09-20", word: "loaf", meaning: "ขนมปังก้อน" },
      { id: "b09-21", word: "passion", meaning: "ความหลงใหล" },
      { id: "b09-22", word: "remind", meaning: "เตือนความจำ" },
      { id: "b09-23", word: "reveal", meaning: "เปิดเผย" },
      { id: "b09-24", word: "ultimate", meaning: "สูงสุด" },
      { id: "b09-25", word: "bun", meaning: "ขนมปังก้อนเล็ก" },
      { id: "b09-26", word: "well-balanced", meaning: "สมดุลดี" },
      { id: "b09-27", word: "full", meaning: "อิ่ม" },
      { id: "b09-28", word: "hot (spicy)", meaning: "เผ็ด" },
      { id: "b09-29", word: "mild", meaning: "รสอ่อน" },
      { id: "b09-30", word: "portion", meaning: "ปริมาณอาหารต่อหนึ่งที่" },
      { id: "b09-31", word: "promising", meaning: "มีอนาคตดี" },
      { id: "b09-32", word: "theme", meaning: "หัวข้อ" },
      { id: "b09-33", word: "graduate", meaning: "สำเร็จการศึกษา" },
      { id: "b09-34", word: "open-minded", meaning: "ใจกว้าง" },
      { id: "b09-35", word: "semester", meaning: "ภาคการศึกษา" },
      { id: "b09-36", word: "stimulate", meaning: "กระตุ้น" },
      { id: "b09-37", word: "supervise", meaning: "ควบคุมดูแล" },
    ],
  },
  {
    deckId: "a2000000-0000-4000-8000-000000000010",
    name: "10 Learning Curve",
    cards: [
      { id: "b10-1", word: "awkward", meaning: "น่าอึดอัด" },
      { id: "b10-2", word: "barely", meaning: "แทบจะไม่" },
      { id: "b10-3", word: "inspire", meaning: "สร้างแรงบันดาลใจ" },
      { id: "b10-4", word: "major in", meaning: "เรียนเอกด้าน" },
      { id: "b10-5", word: "point out", meaning: "ชี้ให้เห็น" },
      { id: "b10-6", word: "rely on", meaning: "พึ่งพา" },
      { id: "b10-7", word: "tricky", meaning: "ยุ่งยาก" },
      { id: "b10-8", word: "valuable", meaning: "มีคุณค่า" },
      { id: "b10-9", word: "according to", meaning: "ตามที่" },
      { id: "b10-10", word: "emphasis", meaning: "การเน้น" },
      { id: "b10-11", word: "feedback", meaning: "ข้อเสนอแนะ" },
      { id: "b10-12", word: "grade", meaning: "เกรด" },
      { id: "b10-13", word: "pressure", meaning: "ความกดดัน" },
      { id: "b10-14", word: "progressive", meaning: "ก้าวหน้า" },
      { id: "b10-15", word: "tutor", meaning: "ครูสอนพิเศษ" },
      { id: "b10-16", word: "well-paid", meaning: "ได้รับค่าตอบแทนดี" },
      { id: "b10-17", word: "whereas", meaning: "ในขณะที่" },
      { id: "b10-18", word: "absence", meaning: "การขาด" },
      { id: "b10-19", word: "ambition", meaning: "ความทะเยอทะยาน" },
      { id: "b10-20", word: "gossip", meaning: "การนินทา" },
      { id: "b10-21", word: "hard-working", meaning: "ขยัน" },
      { id: "b10-22", word: "independent", meaning: "เป็นอิสระ" },
      { id: "b10-23", word: "productive", meaning: "มีประสิทธิผล" },
      { id: "b10-24", word: "stand out", meaning: "โดดเด่น" },
      { id: "b10-25", word: "yell", meaning: "ตะโกน" },
    ],
  },
];
