// คำศัพท์ ม.6 อ่านเขียน — ใช้ร่วมกันระหว่างหน้า player กับ server action
// deckId ต้องตรงกับ fixed UUID ใน migration 0009

import type { FlashcardUnit } from "./m5-term-1-data";

export const M6_TERM1_UNITS: FlashcardUnit[] = [
  {
    deckId: "a3000000-0000-4000-8000-000000000001",
    name: "Unit 1 — Biometrics",
    cards: [
      { id: "c01-1", word: "fingerprint", meaning: "ลายนิ้วมือ" },
      { id: "c01-2", word: "immigration inspection", meaning: "การตรวจคนเข้าเมือง" },
      { id: "c01-3", word: "iris", meaning: "ม่านตา" },
      { id: "c01-4", word: "law enforcement agent", meaning: "เจ้าหน้าที่บังคับใช้กฎหมาย / เจ้าหน้าที่ตำรวจ" },
      { id: "c01-5", word: "passports", meaning: "หนังสือเดินทาง" },
      { id: "c01-6", word: "hacker", meaning: "แฮกเกอร์ / ผู้เจาะระบบคอมพิวเตอร์" },
      { id: "c01-7", word: "signature", meaning: "ลายเซ็น" },
      { id: "c01-8", word: "facial recognition", meaning: "การจดจำใบหน้า" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000002",
    name: "Unit 2 — Cryptocurrency",
    cards: [
      { id: "c02-1", word: "cash", meaning: "เงินสด" },
      { id: "c02-2", word: "digital wallet", meaning: "กระเป๋าเงินดิจิทัล" },
      { id: "c02-3", word: "account book", meaning: "สมุดบัญชี" },
      { id: "c02-4", word: "purchase", meaning: "ซื้อ / การซื้อ" },
      { id: "c02-5", word: "cybercrime", meaning: "อาชญากรรมไซเบอร์" },
      { id: "c02-6", word: "access", meaning: "เข้าถึง / การเข้าถึง" },
      { id: "c02-7", word: "computer server", meaning: "เซิร์ฟเวอร์คอมพิวเตอร์" },
      { id: "c02-8", word: "blockchain", meaning: "บล็อกเชน / ระบบเก็บข้อมูลแบบบล็อกเชน" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000003",
    name: "Unit 4 — Helping Society",
    cards: [
      { id: "c04-1", word: "community member", meaning: "สมาชิกในชุมชน" },
      { id: "c04-2", word: "in addition to", meaning: "นอกจากนั้น / นอกเหนือจาก" },
      { id: "c04-3", word: "less familiar", meaning: "ไม่คุ้นเคยมากนัก" },
      { id: "c04-4", word: "founder", meaning: "ผู้ก่อตั้ง" },
      { id: "c04-5", word: "poverty", meaning: "ความยากจน" },
      { id: "c04-6", word: "repay", meaning: "ชำระคืน / ใช้คืน" },
      { id: "c04-7", word: "start up", meaning: "เริ่มต้น / ก่อตั้งธุรกิจ" },
      { id: "c04-8", word: "profit", meaning: "กำไร" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000004",
    name: "Unit 5 — Helping Environment",
    cards: [
      { id: "c05-1", word: "atmosphere", meaning: "ชั้นบรรยากาศ" },
      { id: "c05-2", word: "carbon emissions", meaning: "การปล่อยก๊าซคาร์บอน" },
      { id: "c05-3", word: "fossil fuels", meaning: "เชื้อเพลิงฟอสซิล" },
      { id: "c05-4", word: "distant", meaning: "ห่างไกล" },
      { id: "c05-5", word: "industrial", meaning: "เกี่ยวกับอุตสาหกรรม" },
      { id: "c05-6", word: "logistics", meaning: "โลจิสติกส์ / การขนส่งและจัดการสินค้า" },
      { id: "c05-7", word: "steep", meaning: "สูงชัน / เพิ่มขึ้นอย่างรวดเร็ว" },
      { id: "c05-8", word: "ultimate", meaning: "ที่สำคัญที่สุด / ขั้นสูงสุด / ท้ายที่สุด" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000005",
    name: "Unit 6 — Tourism",
    cards: [
      { id: "c06-1", word: "tourism", meaning: "การท่องเที่ยว" },
      { id: "c06-2", word: "animal reserve", meaning: "เขตอนุรักษ์สัตว์" },
      { id: "c06-3", word: "ancient ruin", meaning: "ซากโบราณสถาน" },
      { id: "c06-4", word: "destination", meaning: "จุดหมายปลายทาง" },
      { id: "c06-5", word: "damage", meaning: "ความเสียหาย / ทำให้เสียหาย" },
      { id: "c06-6", word: "ecosystem", meaning: "ระบบนิเวศ" },
      { id: "c06-7", word: "staff", meaning: "พนักงาน / เจ้าหน้าที่" },
      { id: "c06-8", word: "close down", meaning: "ปิดกิจการ / ปิดตัวลง" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000006",
    name: "Unit 7 — Augmented Reality",
    cards: [
      { id: "c07-1", word: "accessible", meaning: "เข้าถึงได้ง่าย" },
      { id: "c07-2", word: "augmentation", meaning: "การเพิ่ม / การเสริม" },
      { id: "c07-3", word: "enhancement", meaning: "การปรับปรุง / การทำให้ดีขึ้น" },
      { id: "c07-4", word: "futuristic", meaning: "ล้ำสมัย / เหมือนโลกอนาคต" },
      { id: "c07-5", word: "imagination", meaning: "จินตนาการ" },
      { id: "c07-6", word: "pop up", meaning: "ปรากฏขึ้นทันที" },
      { id: "c07-7", word: "sensation", meaning: "สิ่งที่ได้รับความสนใจอย่างมาก / ความรู้สึก" },
      { id: "c07-8", word: "superimpose", meaning: "วางภาพซ้อนทับ" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000007",
    name: "Unit 8 — Advertising",
    cards: [
      { id: "c08-1", word: "underlying", meaning: "ที่อยู่เบื้องหลัง / พื้นฐาน" },
      { id: "c08-2", word: "identify", meaning: "ระบุ / จำแนก" },
      { id: "c08-3", word: "focus", meaning: "มุ่งเน้น / จุดสนใจ" },
      { id: "c08-4", word: "go to", meaning: "ไปสู่ / ใช้ในวลี" },
      { id: "c08-5", word: "leave it", meaning: "ปล่อยไว้ / ทิ้งไว้" },
      { id: "c08-6", word: "suitable", meaning: "เหมาะสม" },
      { id: "c08-7", word: "hard", meaning: "อย่างหนัก / ยาก / เข้มข้น" },
      { id: "c08-8", word: "by", meaning: "โดย / ด้วย / ใช้ในวลี" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000008",
    name: "Unit 9 — Attracting Visitors",
    cards: [
      { id: "c09-1", word: "importance", meaning: "ความสำคัญ" },
      { id: "c09-2", word: "injects", meaning: "อัดฉีด / ใส่เข้าไป" },
      { id: "c09-3", word: "minerals", meaning: "แร่ธาตุ" },
      { id: "c09-4", word: "namely", meaning: "กล่าวคือ / ได้แก่" },
      { id: "c09-5", word: "nation-wide coverage", meaning: "การครอบคลุมทั่วประเทศ" },
      { id: "c09-6", word: "rely heavily on", meaning: "พึ่งพาอย่างมาก" },
      { id: "c09-7", word: "set aside", meaning: "กันไว้ / จัดสรรไว้" },
      { id: "c09-8", word: "showcases", meaning: "แสดงให้เห็น / จัดแสดง" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000009",
    name: "Unit 10 — Money",
    cards: [
      { id: "c10-1", word: "banknotes", meaning: "ธนบัตร" },
      { id: "c10-2", word: "commerce", meaning: "การค้า / พาณิชย์" },
      { id: "c10-3", word: "peer-to-peer", meaning: "ระหว่างบุคคลกับบุคคลโดยตรง" },
      { id: "c10-4", word: "rural area", meaning: "พื้นที่ชนบท" },
      { id: "c10-5", word: "stall", meaning: "แผงขายของ / ร้านเล็ก ๆ" },
      { id: "c10-6", word: "swipe", meaning: "ปัด / รูดบัตร / สแกนจ่าย" },
      { id: "c10-7", word: "cashless", meaning: "ไร้เงินสด" },
      { id: "c10-8", word: "malicious", meaning: "มุ่งร้าย / เป็นอันตราย" },
    ],
  },
  {
    deckId: "a3000000-0000-4000-8000-000000000010",
    name: "Unit 11 — Robots",
    cards: [
      { id: "c11-1", word: "attend to", meaning: "ดูแล / จัดการ" },
      { id: "c11-2", word: "programming", meaning: "การเขียนโปรแกรม" },
      { id: "c11-3", word: "medical attention", meaning: "การดูแลทางการแพทย์" },
      { id: "c11-4", word: "trial and error", meaning: "การลองผิดลองถูก" },
      { id: "c11-5", word: "intensive", meaning: "เข้มข้น / เร่งรัด" },
      { id: "c11-6", word: "impractical", meaning: "ใช้งานจริงไม่ได้ / ไม่เหมาะสมในทางปฏิบัติ" },
      { id: "c11-7", word: "imitate", meaning: "เลียนแบบ" },
      { id: "c11-8", word: "take over", meaning: "เข้าควบคุม / รับช่วงต่อ" },
    ],
  },
];
